apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  selector:
    app: hello          # send traffic to every Pod with this label
  ports:
    - port: 80          # the Service listens here
      targetPort: 8080  # your container listens here
